substitutions:
    _REPO: html-to-pdf
steps:

- id: "PUSH DEPLOYMENT IMAGE"
  name: gcr.io/kaniko-project/executor:latest
  args:
  - --destination=gcr.io/$_REPO:${COMMIT_SHA}
  - --destination=gcr.io/$_REPO:${BRANCH_NAME}
  - --cache=true
  - --cache-ttl=6h
options:
      logging: NONE